---

# Variables that a user might want to change
# through the command-line or a parameter file.

# Neo4j Extract Parameters

# Nodes and Edges Neo4j Files loaded from database.
neonodefile: neo4jnodes.csv
neoedgefile: neo4jedges.csv

# The database server's pgcopy directory.
# This *MUST* match the directory
# mapped into the PostgreSQL container.
copy_root: /pgcopy

# The (AWS S3) location of vendor RAW data
# a source for standardisation.
bucket: im-fragnet

# AWS credentials for bucket access
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
