---

version: '3.8'

services:

  fragmentor-controller:
    build:
      context: .
      dockerfile: Dockerfile-controller
      network: host
    image: alanbchristie/fragmentor-controller:latest
    environment:
      FRAGMENTOR_PLAY: standardise
      AWS_ACCESS_KEY_ID: 1234
      AWS_SECRET_ACCESS_KEY: 5678
