---

version: '3.8'

services:

  fragmentor-player:
    build:
      context: .
      dockerfile: Dockerfile-player
      network: host
    image: alanbchristie/fragmentor-player:latest
    environment:
      FRAGMENTOR_PLAY: standardise
      AWS_ACCESS_KEY_ID: 1234
      AWS_SECRET_ACCESS_KEY: 5678
