---

# Graph combination process.
#
# Given one or more vendor or combination extracts this process creates a new Neo4j combination
# (a de-duplicated combination of the various node and edge files)
#
# The playbook: -
#
# - Downloads the individual or combined dataset
# - Then depending on the file, processing will:
# - - Concatenates files that contain non-duplicate data.
# - - Merges files that contain data that must be de-duplicated and combined.
# - - De-duplicate files that contain data where no combining is necessary.
# - Processes combined de-duplicated build.
# - Uploads the result as a new combination to S3
#
# Check that required command line parameters have been set:
# - deployment
# - Parameter file file containing vendor(s) and version(s) has been created.
#
#  e.g.
#   extracts:
#       - lib:
#           vendor: 'enamine_ro5'
#           version: 'jun2018'
#           regenerate_index: 'no'
#       - lib:
#           vendor: 'molport'
#           version: '2020-02'
#           regenerate_index: 'yes'
#
#   ansible-playbook site-combine \
#     -e @parameters \
#     -e deployment=development|production
#     -e use_s3 yes/no
#  The use_s3 flag indicates whether files should be downloaded from and uploaded to S3.
#  If this is set to no then the assumption is that a local data directory is used.
#  For deployment=development this would normally be set to "N".

- name: Assert user-variable definitions
  assert:
    that:
    - deployment|string|length > 0
    - deployment|string != 'SetMe'
    - "{{ extracts[0].lib.path|string != 'SetMe'}}"
    - "{{ extracts[0].lib.data_source|string != 'SetMe'}}"
    - "{{ output_data_source|string != 'SetMe'}}"
    fail_msg: You must provide a 'deployment', a list of extracts in a parameter file to combine and an output location.

- name: List input datasets
  debug:
    msg: "{{ item.lib }}"
  loop: "{{ extracts }}"

- import_tasks: initialise.yaml

#- include_tasks: "{{ role_path }}/../utils/tasks/send-mail.yaml"
#  vars:
#    mail_subject: >-
#      Play no. {{ cylc_play_number }} -
#      COLLECTING (1/4) - combination {{ combination_number }}

- import_tasks: download-datasets.yaml
- import_tasks: deduplicate.yaml
- import_tasks: merge.yaml
- import_tasks: concatenate.yaml

- name: Display compress_tasks
  debug:
    var: compress_tasks

- name: Check compress tasks finished.
  async_status: jid={{ compress_result.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: "{{ (compress_timeout_minutes|int /
            compress_poll_period_minutes|int )|int }}"
  delay: "{{ compress_poll_period_minutes|int * 60 }}"
  loop: "{{ compress_tasks }}"
  loop_control:
    loop_var: compress_result

# Finalise report
- name: Write line to report
  blockinfile:
    marker: "<!-- {combination-init} ANSIBLE MANAGED BLOCK -->"
    path: "{{ log_path }}/combination_report.html"
    block: |
      <p>Combine play ended on: {{ now(utc=True).isoformat() }}</p>

- import_tasks: finalise-{{ output_data_source }}.yaml
