---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Set DB user account
  set_fact:
    user_account: "{{ database[deployment].db_user_account }}"

- name: Create database user account
  user:
    name: "{{ user_account }}"
    groups: docker
    append: yes

- name: Adding "{{ database[deployment].db_user_account }}" to docker group
  user:
    name: "{{ database[deployment].db_user_account }}"
    groups: docker
    append: yes
  become: yes

- name: Ensure required Python modules
  pip:
    name: "{{ item }}"
  loop:
  - docker
  - docker-py
  become: yes

- name: Write compose file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ ansible_env.HOME }}/docker-compose.yaml"
  become: yes
  become_user: "{{ database[deployment].db_user_account }}"
