---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Set DB user account
  set_fact:
    user_account: "{{ database[deployment].db_user_account }}"

- name: Create database user account
  user:
    name: "{{ user_account }}"
    groups: docker
    append: yes

- name: Adding "{{ user_account }}" to docker group
  user:
    name: "{{ user_account }}"
    groups: docker
    append: yes
  become: yes

- name: Get DB user home
  shell: >
    getent passwd {{ user_account }} | cut -d: -f6
  changed_when: false
  register: db_user_home

- name: Write compose file (to {{ db_user_home.stdout }})
  template:
    src: docker-compose.yaml.j2
    dest: "{{ db_user_home.stdout }}/docker-compose.yaml"
  become: yes
  become_user: "{{ user_account }}"
