---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Set DB user account
  set_fact:
    user_account: "{{ database[deployment].db_user_account }}"

- name: Adding "{{ user_account }}" to docker group
  user:
    name: "{{ database[deployment].db_user_account }}"
    groups: docker
    append: yes
  become: yes

- name: Get DB user home
  shell: >
    getent passwd {{ user_account }} | cut -d: -f6
  changed_when: false
  register: db_user_home

- name: Stop DB
  command: docker compose stop
  args:
    chdir: "{{ db_user_home.stdout }}"
  become: yes
  become_user: "{{ user_account }}"
