---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Adding "{{ database[deployment].db_user_account }}" to docker group
  user:
    name: "{{ database[deployment].db_user_account }}"
    groups: docker
    append: yes
  become: yes

- name: Stop database container
  docker_container:
    name: db
    state: stopped
  become: yes
  become_user: "{{ database[deployment].db_user_account }}"
