---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Stop database container
  docker_container:
    name: db
    state: stopped
  become: yes
  become_user: "{{ database[deployment].db_user_account }}"
