---

- name: Assert user-variable definitions
  assert:
    that:
    - deployment|string|length > 0
    - deployment|string != 'SetMe'
    - restore_file|string|length > 0
    - restore_file|string != 'SetMe'
    fail_msg: You must provide a 'deployment' and a restore_file from the backups to restore to the database.

- import_tasks: restore-{{ deployment }}.yaml
