---

# Variables that a user might want to change
# through the command-line or a parameter file.

# Module to add the inchi key - creates inchi.tab from nodes.csv.
fragnodefile: nodes.csv
inchifile: inchi.csv
inchitab: inchi.tab
isoinchifile: isoinchi.csv
isoinchitab: isoinchi.tab

# Chunk size for loading inchis
inchichunk: 1000000

# Parameters for generating inchis
inchigenchunk: 1000000
nonstandard: n
standard: s
nodefile: node

# Fragmentation Nextflow timeouts -
# note that on production a clean run for molport
# may take 16 hours on the cluster.

nextflow_timeout_minutes: 360
nextflow_poll_period_minutes: 10
