---

- name: Extract nonisomol smiles for this source_id with missing inchi information to isoinchfile
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (SELECT non.smiles FROM nonisomol non\
                 WHERE non.inchis IS NULL
                   AND EXISTS (SELECT 1 FROM mol_source m WHERE non.id = m.nonisomol_id
                   AND m.source_id = {{ source_id }}))
                    TO '{{ fragpath }}/fragment/{{ inchifile }}'"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"


