---

- name: Variable sanity-check
  assert:
    that:
    - inchichunk|int > 0

- name: Check inputfile present
  stat:
    path: "{{ fragpath }}/fragment/{{ fragnodefile }}"
  register: nodesfile_result

- name: Assert nodesfile
  assert:
    that:
    - nodesfile.stat.exists

- name: run python generate_inchi

#
# python -m frag.network.scripts.generate_inchi -i $FRAGPATH/fragment/$FRAGNODEFILE -o $FRAGPATH/fragment/$INCHITAB -n -s -node
#

- name: Run python generate_inchi
  script: frag.network.scripts.generate_inchi.py
  args:
    executable: python3


