---

- name: Extract nonisomol smiles for this source_id with missing inchi information to inchfile
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (SELECT non.smiles FROM nonisomol non
                 WHERE non.inchis IS NULL)
                    TO '{{ fragpath }}/fragment/{{ inchifile }}'"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"

#
# python -m frag.network.scripts.generate_inchi -i $FRAGPATH/fragment/$FRAGNODEFILE -o $FRAGPATH/fragment/$INCHITAB -n -s
#

- name: Run python generate_inchi
  script: generate_inchi.py -i {{ fragpath }}/fragment/{{ inchifile }} -o {{ fragpath }}/fragment/{{ inchitab }} -n -s


