---

- name: Check inputfile present
  stat:
    path: "{{ fragpath }}/fragment/{{ fragnodefile }}"
  register: nodesfile_result

- name: Assert nodesfile
  assert:
    that:
    - nodesfile.stat.exists
#
# python -m frag.network.scripts.generate_inchi -i $FRAGPATH/fragment/$FRAGNODEFILE -o $FRAGPATH/fragment/$INCHITAB -n -s -node
#
- name: Run python generate_inchi
  script: generate_inchi.py -i {{ fragpath }}/fragment/{{ fragnodefile }} -o {{ fragpath }}/fragment/{{ inchitab }} -n -s -node



