---

- name: Display chunk
  debug:
    var: item

- name: (Re) create i_noniso_inchi table
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f85_create_i_noniso_inchi.sql"
    autocommit: yes

- name: Copy chunk to i_noniso_inchi
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=on --set ON_ERROR_STOP=on
     -c "\COPY i_noniso_inchi(smiles, sinchik, sinchis, ninchik, ninchis)
         FROM '{{ item }}';"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"

- name: Update inchi keys for nonisomol
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f85_update_noniso_inchi.sql"
    autocommit: no
