---

# Splits the nodes file into 'chunks'
# and then call on the 'chunk' loader
# for each file created to load into the database

- name: Variable sanity-check
  assert:
    that:
    - inchichunk|int > 0

- name: Check inputfile present
  stat:
    path: "{{ fragpath }}/fragment/{{ inchitab }}"
  register: inchitab_result

- name: Assert inchitab
  assert:
    that:
    - inchitab_result.stat.exists

- name: Split inchtab file
  shell: >-
    cat {{ inchitab }} | split -d -l {{ inchichunk }} - inchichunk_
  args:
    chdir: "{{ fragpath }}/fragment"

- name: Load inchichunk
  include_tasks: load-nonisomol-chunk.yaml
  with_fileglob:
  - "{{ fragpath }}/fragment/inchichunk_*"
