---

# Check that a version has been defined.
# the most convenient way of doing this is via the command-line: -
#
#   ansible-playbook site-inchi \
#     -e deployment=production
#     -e runpath=data/share-2/run01
#

- name: Assert user-variable definitions
  assert:
    that:
    - deployment|string|length > 0
    - deployment|string != 'SetMe'
    - runpath|string|length > 0
    - runpath|string != 'SetMe'
    fail_msg: You must provide a 'deployment', and default run path where files will be stored.

- block:

  - import_tasks: initialise.yaml
  - import_tasks: gen-nonisomol-inchi-database.yaml
  - import_tasks: load-nonisomol-inchi.yaml
  - import_tasks: gen-isomol-inchi-database.yaml
  - import_tasks: load-isomol-inchi.yaml

  module_defaults:
    postgresql_query:
      login_host: "{{ database_login_host }}"
      port: "{{ database[deployment].port }}"
      db: "{{ database[deployment].db }}"
      login_user: "{{ database[deployment].login_user }}"
      login_password: "{{ database[deployment].login_password }}"
    postgresql_copy:
      login_host: "{{ database_login_host }}"
      port: "{{ database[deployment].port }}"
      db: "{{ database[deployment].db }}"
      login_user: "{{ database[deployment].login_user }}"
      login_password: "{{ database[deployment].login_password }}"

# Backup database if required using the site-backup play.
- include_role:
    name: backup
  when: add_backup|bool
