---
# Install modules to perform the backup
- name: Install requirements
  pip:
    name:
    - python-dateutil==2.8.1
    - boto3==1.12.49
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ database[deployment].backup_directory }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes

# sudo docker run --rm -v /pgdata-backup:/backup -e PGHOST=130.246.214.154 -e PGUSER=fragmentor -e PGADMINPASS=bullfinch informaticsmatters/sql-backup:2020.4
- name: Start backup
  docker_container:
    name: db-backup
    image: "{{ backup_container_image }}:{{ backup_container_tag }}"
    state: started
    restart_policy: no
    env:
      PGHOST: "{{ database[deployment].login_host }}"
      PGUSER: "{{ database[deployment].login_user }}"
      PGADMINPASS: "{{ database[deployment].login_password }}"
      BACKUP_COUNT: "{{ database[deployment].backup_count }}"
    volumes:
    - "{{ database[deployment].backup_directory }}:/backup"
    network_mode: host
  become: yes
  delegate_to: "{{ groups['dbservers'][0] }}"
