---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml

reppath: "{{ role_path }}/../../.."

# The following is used (amongst other things)
# to load vendor-specific variables...
vendor: SetMe
# The user is required tp specify the version on the command-line
version: SetMe

# Save the extract
# (typically compressing and saving to S3)
save_extract: yes

# Whether an index or recursive extract is to be used.
# The recursive sql statements are not safe for larger vendors.
extract: index
# Whether to load or use an existing index.
load_index: yes

