---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml

reppath: "{{ role_path }}/../../.."

# The following is used (amongst other things)
# to load vendor-specific variables from a specified parameters file - see extract-parameters.template...
extracts:
    - lib:
        vendor: 'SetMe'
        version: 'SetMe'
        regenerate_index: 'SetMe'

# Save the extract
# (typically compressing and saving to S3)
save_extract: no

# In the case of a combined extract, which of the vendor specific files to use.
combined_vendor: molport
