---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml

reppath: "{{ role_path }}/../../.."

# The following is used (amongst other things)
# to load vendor-specific variables from a specified parameters file - see extract-parameters.template...
extracts:
- lib:
    vendor: 'SetMe'
    version: 'SetMe'
    regenerate_index: 'SetMe'

# Save the extract
# (typically compressing and saving to S3)
save_extract: yes

# In the case of a combined extract, which of the vendor specific files to use.
combined_vendor: molport

# Only for restart.
# If this is set to yes (the default) the index table will be deleted,
# Otherwise the table will be left and processing will restart using this data.
# It will speed up processing in edges are already present.
# If a proper restart point is required, this functionality can be reconsidered.
drop_index_table: yes

# Whether the index should be built in serial or parallel.
index_build: parallel
