---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
#
# The deployment value should be an entry in the database map (see below)
deployment: SetMe

# Erase any files/content generated in a prior run?
# If set to yes this tends to remove temporary data directories,
# it does not erase or adjust databases or tables -
# it's simply about a clean 'disk'.
clean_start: yes

# The tag of the fragmentation container,
# used for a number of nextflow workflows.
nextflow_container_tag: molport-04

# Database credentials.
# A map of variables based on deployment target.
database:
  development:
    login_host: localhost
    port: 5432
    db: mydatabase
    login_user: postgres
    login_password: 1234
    copy_directory: /var/lib/postgresql/data
    db_user_account: postgres
  production:
    login_host: 192.168.253.51
    port: 5432
    db: fairmolecules
    login_user: fragmentor
    login_password: bullfinch
    copy_directory: /pgcopy
    db_user_account: fragmentor

# Chunk size to control size of transactions in
# uploading standardised file data to database
standchunk: 1000000

# The database server user account
#db_user_account: fragmentor
