---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
deployment: development

# Erase any files/content generated in a prior run?
# If set to yes this tends to remove temporary data directories,
# it does not erase or adjust databases or tables -
# it's simply about a clean 'disk'.
clean_start: yes

# The tag of the fragmentation container,
# used for a number of nextflow workflows.
nextflow_container_tag: molport-04

# Database credentials.
# A map of variables based on deployment target.
database:
  development:
    login_host: localhost
    port: 5432
    db: mydatabase
    login_user: postgres
    login_password: 1234
  production:
    login_host: 192.168.253.65
    port: 5432
    db: fairmolecules
    login_user: fragmentor
    login_password: bullfinch

# Chunk size to control size of transactions in uploading standardised file data to database,
standchunk: 1000000