---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
#
# The deployment value should be an entry in the database map (see below)
deployment: SetMe

# Erase any files/content generated in a prior run?
# If set to yes this tends to remove temporary data directories,
# it does not erase or adjust databases or tables -
# it's simply about a clean 'disk'.
clean_start: yes

# If set to yes this tends to remove temporary/work data directories.
# Not essential files.
clean_finish: no

# The tag of the fragmentation container,
# used for a number of nextflow workflows.
nextflow_container_tag: combine-06

# Cloud provider for the database server.
# Typically one of 'openstack' or 'aws'
database_cloud_provider: openstack

# The hostname of the database server.
# One of production or development.
database_login_host: SetMe

# Database credentials.
# A map of variables based on deployment target.
#
# Caution:  Ensure that the 'production.copy_directory' matches what's
#           used in 'db_devices.pg_copy.mount_path'
#           (see 'roles/configure/defaults/main.yaml')
database:
  development:
    port: 5432
    db: mydatabase
    login_user: postgres
    login_password: 1234
    copy_directory: /var/lib/postgresql/data
    backup_directory: /home/duncan/Documents/pgdata-backup
    backup_count: 2
    db_user_account: postgres
  production:
    port: 5432
    db: fairmolecules
    login_user: fragmentor
    login_password: bullfinch
    copy_directory: /pgcopy
    backup_directory: /pgdata-backup
    backup_count: 2
    db_user_account: fragmentor

# A default set of devices.
# Normally specified in a host-specific file in host_vars
#
# The DB server's database, backup, pgcopy and wal volume
# devices, and mount-points
db_devices:
  pg_data:
    device:
    mount_path: /pgdata
  pg_copy:
    device:
    mount_path: /pgcopy
  pg_wal:
    device:
    mount_path: /pgwal
  pg_backup:
    device:
    mount_path: /pgdata-backup

# Hardware sizing - used to calculate size of chunks in standardization/fragmentation.
# A map of variables based on deployment target.
hardware:
  development:
    # Parallel_jobs is used in calculating chunk sizes for processing -
    # the normal assumption is that twice as many jobs are created as cores
    # are used. If this is less than cluster_cores, then not all the cluster
    # will be used. It is usually safe to set the parallel_jobs and
    # cluster_cores to the same value.
    parallel_jobs: 8
    # Cluster cores is used in the nextflow_config.
    # It defines the size of the cluster to use.
    cluster_cores: 8
    # Sort memory defines the minimum memory required for deduplication/sorting..
    sort_memory: 8MB
    # Number of connections to postgres -
    # note that this should be less than max_worker_processes in start-database.yaml.
    postgres_jobs: 6
  production:
    # 100 parallel jobs/cores should be sufficient to process all but the
    # largest libraries (full enamine/molport load).
    # For role combine, ideally this might be increased
    # when combining large databases - otherwise there might be a timeout.
    parallel_jobs: 100
    cluster_cores: 100
    sort_memory: 8GB
    postgres_jobs: 18

# Vendor defaults.
# A map of defaults based on the vendor and library.
vendors:
  xchem_dsip:
    # Used for sizing timeouts and processing parameters
    approx_vendor_molecules: 800
    # Total time (in minutes) across all CPUs -
    # Used for sizing timeouts and processing parameters
    est_total_fragmentation_time: 10
    # Minimum heavy atom count for extraction/fragmentation processing
    fragminhac: 0
    # Maximum heavy atom count for extraction/fragmentation processing
    fraghac: 36
    # Maximum frag cycles for fragmentation processing
    fragmaxfrags: 12
    # Limit for partial fragmentation processing (not operational)
    fraglimit: 0
    # Extract Playbook: Chunk of molecules to be processed before insert to index
    # This is a sensitive value - settings for each vendor should be tuned.
    # So the values below are set based on the number of edges per mol_source value
    # and validated by testing.
    indexchunksize: 100
    # Total time (in minutes) to build index (will be divided by number of postgres_jobs)
    index_build_time: 10
  xchem_spot:
    approx_vendor_molecules: 96
    est_total_fragmentation_time: 10
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    indexchunksize: 100
    index_build_time: 10
  xchem_probe:
    approx_vendor_molecules: 239
    est_total_fragmentation_time: 10
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    indexchunksize: 100
    index_build_time: 10
  chemspace_bb:
    approx_vendor_molecules: 18000000
    est_total_fragmentation_time: 7500
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    indexchunksize: 2000
    index_build_time: 480
  molport:
    approx_vendor_molecules: 8000000
    est_total_fragmentation_time: 360000
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    indexchunksize: 300
    index_build_time: 4320
  enamine_ro5:
    approx_vendor_molecules: 40000000
    est_total_fragmentation_time: 720000
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    indexchunksize: 300
    index_build_time: 17280

# The tag of the fragmentation container,
neo4j_graph_version: 2019-12-18.2

# Email configuration
#
# Credentials to enable SMTP email transmission.
# All of there are expected to be defined in the user's parameters file
# or, via the environment.
# If any of them are unset/blank, mail is not sent.
# Username is the owner of the email account, not a recipient.
# mail_recipients is a comma-separated list of email addresses.
mail_host: "{{ lookup('env', 'GRAPH_MAIL_HOST') }}"
mail_port: "{{ lookup('env', 'GRAPH_MAIL_PORT') or '587' }}"
mail_username: "{{ lookup('env', 'GRAPH_MAIL_USERNAME') }}"
mail_password: "{{ lookup('env', 'GRAPH_MAIL_PASSWORD') }}"
mail_recipients: "{{ lookup('env', 'GRAPH_MAIL_RECIPIENTS') }}"
