---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
#
# The deployment value should be an entry in the database map (see below)
deployment: SetMe

# Erase any files/content generated in a prior run?
# If set to yes this tends to remove temporary data directories,
# it does not erase or adjust databases or tables -
# it's simply about a clean 'disk'.
clean_start: yes

# The tag of the fragmentation container,
# used for a number of nextflow workflows.
nextflow_container_tag: molport-04

# The process id is the commit id of the fragmentation container,
# Used in the extract file
process_id: Fragmentor-c883d74

# Database credentials.
# A map of variables based on deployment target.
#
# Caution:  Ensure that the 'production.copy_directory' matches what's
#           used in 'db_devices.pg_copy.mount_path'
#           (see 'roles/configure/defaults/main.yaml')
database:
  development:
    login_host: localhost
    port: 5432
    db: mydatabase
    login_user: postgres
    login_password: 1234
    copy_directory: /var/lib/postgresql/data
    db_user_account: postgres
  production:
    login_host: 130.246.214.154
    port: 5432
    db: fairmolecules
    login_user: fragmentor
    login_password: bullfinch
    copy_directory: /pgcopy
    db_user_account: fragmentor

# Vendor defaults.
# A map of defaults based on the vendor and library.
vendors:
  xchem_dsip:
    # Minimum heavy atom count for extraction/fragmentation processing
    fragminhac: 0
    # Maximum heavy atom count for extraction/fragmentation processing
    fraghac: 36
    # Maximum frag cycles for fragmentation processing
    fragmaxfrags: 12
    # Limit for partial fragmentation processing (not operational)
    fraglimit: 0
    # Number of chunks to process before commit - how many inserts build up
    # Chunk of molecules to be processed before insert to index
    # This is a sensitive value that seems to be optimally around 22000 edges per chunk.
    # # So the values below are set based on the number of edges per mol_source.
    extractchunksize: 800
  chemspace_bb:
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    extractchunksize: 2000
  molport:
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    extractchunksize: 300
  enamine_r05:
    fragminhac: 0
    fraghac: 36
    fragmaxfrags: 12
    fraglimit: 0
    extractchunksize: 300

# The tag of the fragmentation container,
neo4j_graph_version: 2019-12-18.2

# Chunk size to control size of transactions in
# uploading standardised file data to database
standchunk: 1000000
