---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
deployment: development

# The tag of the fragmentation container,
# used for a number of nextflow workflows.
nextflow_container_tag: molport-04

# Database credentials.
# A map of variables based on deployment target.
database:
  development:
    login_host: localhost
    port: 5432
    db: mydatabase
    login_user: postgres
    login_password: 1234
  production:
    login_host: localhost
    port: 5432
    db: fairmolecules
    login_user: postgres
    login_password: hello
