---

# Variables shared with all roles

# The deployment type.
# This is used to select material based on whether
# we're launching plays for: -
# - development
# - production
deployment: development

# Tye tag of the fragmentation container,
# used for a number of jobs.
nextflow_container_tag: molport-04

database:
  development:
    hostname: localhost
    port: 5432
    databsse: mydatabase
    username: postgres
    password: 1234
  production:
    hostname: localhost
    port: 5432
    databsse: fairmolecules
    username: postgres
    password: hello
