---

- name: Create frag databsse
  postgresql_query:
    login_host: "{{ database[deployment].login_host }}"
    port: "{{ database[deployment].port }}"
    db: "{{ database[deployment].db }}"
    login_user: "{{ database[deployment].login_user }}"
    login_password: "{{ database[deployment].login_password }}"
    path_to_script: p10_create_frag_database.sql
    autocommit: yes
