---

- name: Check deployment definition
  assert:
    that: deployment|string != 'SetMe'

- name: Start database container
  docker_container:
    name: db
    image: "{{ db_container_image }}:{{ db_container_tag }}"
    command: >-
      -c 'shared_buffers={{ db_shared_buffers_g }}GB'
      -c 'work_mem={{ db_work_mem_m }}MB'
      -c 'autovacuum_max_workers=24'
      -c 'max_worker_processes=24'
      -c 'max_parallel_workers=24'
      -c 'max_parallel_workers_per_gather=8'
      -c 'sychronous_commit=on'
    shm_size: "{{ db_shared_buffers_g|int * 2 }}G"
    state: started
    env:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "{{ database[deployment].login_user }}"
      POSTGRES_PASSWORD: "{{ database[deployment].login_password }}"
      POSTGRES_DB: "{{ database[deployment].db }}"
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/wal
    volumes:
    - /pgdata:/var/lib/postgresql/data
    - /pgwal:/var/lib/postgresql/wal
    - /pgcopy:/pgcopy
    exposed_ports:
    - "{{ database[deployment].port }}:5432"
    network_mode: host
  become: yes
  become_user: "{{ db_user_account }}"

- name: Wait for database port
  wait_for:
    port: "{{ database[deployment].port }}"
