---

# Variables that a user might want to change
# through the command-line or a parameter file.

# Fragmentation Parameters

# Fragmentation Nextflow timeouts -
# note that on production a clean run for molport
# may take 16 hours on the cluster.

nextflow_timeout_minutes: 120
nextflow_poll_period_minutes: 1

# Filename of standardised SMILES extracted from i_mols for fragmentation

fragsmifile: nonisomol.smi

# Used for calculation
fragchunksize_calc: 0
nextflow_timeout_calc: 0

# Minimum chunk size for fragmentation processing
fragchunksize: 10

# Safety factor is used in case, for example, other processes are on the machine
safety_factor: 3

# Nodes and Edges Files produced by fragmentation..
fragnodefile: nodes.csv
fragedgefile: edges.csv

# Chunk size for loading edges and nodes
nodechunk: 5000000
edgechunk: 20000000

# This is the threshold at which point it is sensible to drop and recreate
# the indexes on the edge table
# (This takes about an hour and a quarter on production)
edgeindexthreshold: 50000000