---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml
reppath: "{{ role_path }}/../../.."

# Base path for all folders used in the run.
# This should normally be different to the repo path and ideally should start with a "/".
runpath: SetMe

# These have been coded so that they can different to each other, but there is no obvious need at this point.
# Hence they all default to runpath - set in the command line.
# Work directory for standardisation
fragpath: "{{ runpath }}"
# Directory for nextflow work files
nextpath: "{{ runpath }}/nextflow"

# When set to "yes" this will automatically back up the database at the end of the inchi play.
add_backup: yes
