---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml
reppath: "{{ role_path }}/../../.."

# The following is used is store extract files. It is common with the fragment play (at least for now) because
# the inchi processing can be driven from nodes.csv (output from fragmentation step).
fragpath: SetMe


