---

- name: Extract unfragmented smiles for this source_id to fragsmifile
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (SELECT n.smiles FROM nonisomol n
         WHERE NOT EXISTS (SELECT 1 FROM edge e WHERE e.parent_id = n.id)
         AND EXISTS (SELECT 1 FROM mol_source m WHERE n.id = m.nonisomol_id
         AND m.source_id = {{ source_id }})
         AND n.hac <= {{ vendors[vendor].fraghac }} ) TO '{{ fragpath }}/fragment/{{ fragsmifile }}'"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"
