---

- name: Display chunk
  debug:
    var: item

- name: (Re) create i_edge table
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f90_create_i_edges.sql"
    autocommit: yes

- name: Copy chunk to i_edge
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database_login_host }} --echo-all
     --set AUTOCOMMIT=on --set ON_ERROR_STOP=on
     -c "\COPY i_edge(p_smiles, c_smiles, label) FROM '{{ item }}' DELIMITER ',' CSV;"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"

- name: Set indexes
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f90_set_indexes.sql"
    autocommit: yes

- name: Extract new edges into file for loading into the detabase
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database_login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (SELECT np.id, nc.id, ied.label, {{ source_id }}
                  FROM i_edge ied
                  JOIN nonisomol np ON np.smiles = ied.p_smiles
                  JOIN nonisomol nc ON nc.smiles = ied.c_smiles
                 WHERE NOT EXISTS
                   (SELECT 1 FROM edge edg
                     WHERE edg.parent_id = np.id
                       AND edg.child_id  = nc.id)) TO '{{ item }}.new' DELIMITER ',' CSV;"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"
