---

# Splits the nodes file into 'chunks'
# and then call on the 'chunk' loader
# for each file created to load into the database

- name: Log line to report
  blockinfile:
    marker: "<!-- {fragmentation-edge-nodes} ANSIBLE MANAGED BLOCK -->"
    path: "{{ fragpath }}/fragment/fragmentation_summary_report.html"
    block: |
      <h2>Step: Load Fragmented Edges</h2>
      <p>Begin: {{ now(utc=True).isoformat() }}</p>

- name: Variable sanity-check
  assert:
    that:
    - edgechunk|int > 0
    - edgeindexthreshold > 0

- name: Check inputfile present
  stat:
    path: "{{ fragpath }}/fragment/{{ fragedgefile }}"
  register: fragedgefile_result

- name: Assert fragedgefile
  assert:
    that:
    - fragedgefile_result.stat.exists

- name: Count edges
  shell: wc -l < {{ fragpath }}/fragment/{{ fragedgefile }}
  register: edgecount_result

- name: Set edge_count
  set_fact:
    edge_count: "{{ edgecount_result.stdout }}"

- name: Display number of edges
  debug:
    var: edge_count

- name: Log line to report
  blockinfile:
    marker: "<!-- {fragmentation-edge-nodes} ANSIBLE MANAGED BLOCK -->"
    path: "{{ fragpath }}/fragment/fragmentation_summary_report.html"
    block: |
      <p><table>
      <tr><th>Parameter</th><th>Value</th></tr>
      <tr><td>Fragmented Edges to process</td><td>{{ edge_count }}</td></tr>
      <tr><td>Edge Chunk Size</td><td>{{ edgechunk }}</td></tr>
      <tr><td>Edge Index Threshold</td><td>{{ edgeindexthreshold }}</td></tr>
      </table></p>

- name: Split edge file
  shell: >-
    cat {{ fragedgefile }} | split -d -l {{ edgechunk }} - edgechunk_
  args:
    chdir: "{{ fragpath }}/fragment"

- name: Extract edges for loading
  include_tasks: load-extract-edges-chunk.yaml
  with_fileglob:
  - "{{ fragpath }}/fragment/edgechunk_*"

- name: Drop indexes for speed
  postgresql_query:
    query: DROP INDEX IF EXISTS ix_edge_parent_id
    autocommit: yes
  when: edge_count|int > edgeindexthreshold


- name: Load edges into database
  include_tasks: load-edges-chunk.yaml
  with_fileglob:
  - "{{ fragpath }}/fragment/edgechunk_*.new"

# Node that this may be moved to a clearup job as I don't think the indexes are required for the neo4j extract - to be tested.

- name: Recreate indexes
  postgresql_query:
    query: CREATE INDEX ix_edge_parent_id ON public.edge USING btree (parent_id)
    autocommit: yes
  when: edge_count|int > edgeindexthreshold

- name: Log line to report
  blockinfile:
    marker: "<!-- {fragmentation-edge-nodes} ANSIBLE MANAGED BLOCK -->"
    path: "{{ fragpath }}/fragment/fragmentation_summary_report.html"
    block: |
      <p>Load: {{ now(utc=True).isoformat() }}</p>
