---

- name: Copy edge chunk to edge ({{ item }})
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database_login_host }} --echo-all
     --set AUTOCOMMIT=on --set ON_ERROR_STOP=on
     -c "\COPY edge(parent_id, child_id, label, source_id)
         FROM '{{ item }}' DELIMITER ',' CSV;"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"
