---


- name: Display vendor
  debug:
    msg: "{{ item.lib.vendor }}"

- name: Display vendor
  debug:
    msg: "{{ item.lib.version }}"

- name: Display vendor
  debug:
    msg: "{{ item.lib.regenerate_index }}"

- name: Display source_id
  debug:
    msg: "{{ source_id[vendor_index] }}"

- name: (Re) create o_edge_<vendor> table
  postgresql_query:
    query: >-
      drop table if exists public.o_edge_{{ item.lib.vendor }};
      create TABLE public.o_edge_{{ item.lib.vendor }} (PRIMARY KEY (parent_id, child_id, label)) inherits (o_edge_parent);
    autocommit: yes
  when: item.lib.regenerate_index|bool

- name: Retrieve number of molecules to extract
  postgresql_query:
    query: select count(*) from mol_source where source_id = {{ source_id[vendor_index] }};
    autocommit: no
  register: query_result

- name: Variable sanity-check
  assert:
    that:
    - "{{ query_result.query_result[0].count|int > 0 }}"

- name: Set no_of_molecules
  set_fact:
     no_of_molecules: "{{ query_result.query_result[0].count  }}"

# This calls a stored procedure that is stored in p10_create_frag_database
- name: Load o_edge_vendor table
  postgresql_query:
    query: >-
      call extract_o_edge_vendor({{ source_id[vendor_index] }}, {{ vendors[item.lib.vendor].extractchunksize }}, 0, {{ no_of_molecules }}, 'o_edge_{{ item.lib.vendor }}' );
    autocommit: yes
  when: item.lib.regenerate_index|bool
