---

- name: Erase directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ neo4jpath }}/neo4jextract"
  when: clean_start|bool

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ neo4jpath }}/neo4jextract"


- name: Retrieve source_id
  postgresql_query:
    query: select max(id) from source where name = '{{ vendor }}' and version = '{{ version }}';
    autocommit: no
  register: query_result

- debug:
    var: query_result

- name: Set source_id
  set_fact:
    source_id: "{{ query_result.query_result[0].max }}"

- name: Display source_id
  debug:
    var: source_id
