
- name: Check and store source_id for each vendor
  include_tasks: check_source_id.yaml
  loop: "{{ extracts }}"

# Erase and create the neo4j extract directory...

- name: Remove extract path
  file:
    path: "{{ copy_root }}/extract"
    state: absent
    owner: "{{ database[deployment].db_user_account }}"
    group: "{{ database[deployment].db_user_account }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes
  when: deployment=="production"

- name: Ensure extract path
  file:
    path: "{{ copy_root }}/extract"
    state: directory
    mode: 0777
    owner: "{{ database[deployment].db_user_account }}"
    group: "{{ database[deployment].db_user_account }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes
  when: deployment=="production"
