---

- name: Retrieve source_id
  postgresql_query:
    query: select max(id) from source where name = '{{ vendor }}' and version = '{{ version }}';
    autocommit: no
  register: query_result

- debug:
    var: query_result

- name: Set source_id
  set_fact:
    source_id: "{{ query_result.query_result[0].max }}"

- name: Display source_id
  debug:
    var: source_id

- name: Variable sanity-check
  assert:
    that:
    - source_id|int > 0

# Erase and create the neo4j extract directory...

- name: Remove extract path
  file:
    path: "{{ copy_root }}/extract"
    state: absent
    owner: "{{ database[deployment].db_user_account }}"
    group: "{{ database[deployment].db_user_account }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes
  when: deployment=="production"

- name: Ensure extract path
  file:
    path: "{{ copy_root }}/extract"
    state: directory
    mode: 0777
    owner: "{{ database[deployment].db_user_account }}"
    group: "{{ database[deployment].db_user_account }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
  become: yes
  when: deployment=="production"


