---

- name: Extract NEO4J node information for this source_id to neonodefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_nodes_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      OUTFILE: "{{ copy_root }}/{{ neonodefile }}"
    autocommit: no

- name: Extract NEO4J edge information for this source_id to neoedgefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_edges_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      OUTFILE: "{{ copy_root }}/{{ neoedgefile }}"
    autocommit: no
