---

- name: Extract supporting information for this source_id / extract to various files
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_supporting_info_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      GRAPHVERSION: "{{ neo4j_graph_version }}"
      PROCESSID: "{{ process_id }}"
      ISOMOLEDGEFILE: "{{ copy_root }}/extract/{{ isomoledgefile }}"
      ISOMOLNODEFILE: "{{ copy_root }}/extract/{{ isomolnodefile }}"
      ISOSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ isosupmoledgefile }}"
      MOLSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ molsupmoledgefile }}"
      SUPNODEFILE: "{{ copy_root }}/extract/{{ supnodefile }}"
      SUPMOLNODEFILE: "{{ copy_root }}/extract/{{ supmolnodefile }}"
    autocommit: no

- name: Extract vendor specific supporting information for this source_id / extract
  postgresql_query:
    path_to_script: "{{ role_path }}/files/{{ vendor }}/f100-neo4j-vendor-suppliermol.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"
    autocommit: no

- name: Extract molecule-inchi-edges for this source_id / extract
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_mol_inchi_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      MOLINCHIEDGEFILE: "{{ copy_root }}/extract/{{ molinchiedgefile }}"
    autocommit: no

- name: Extract inchis for this source_id / extract
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_inchi_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      INCHIIDFILE: "{{ copy_root }}/extract/{{ inchiidfile }}"
    autocommit: no
