---

- name: Create a comma separated list of source_ids
  set_fact:
     source_ids:  "{{ source_id | join(',') }}"

- name: test
  debug:
      msg: "{{ source_ids }}"

- name: Create a list of the table names involved
  set_fact:
     source_table:  "{{ source_table + ['_'.join(('o_edge',item.lib.vendor))] }}"
  loop: "{{ extracts }}"

- name: show list
  debug:
      msg: "{{ source_table }}"

- name: Create a comma separated list of the table names
  set_fact:
     source_tables:  "'{{ source_table | map ('quote') | join(', ') }}'"

#- name: Create a comma separated list of the table names
#  set_fact:
#     source_tables: "'({ source_table | join(', ') }}'"

- name: show string
  debug:
      msg: "{{ source_tables }}"

- name: Extract NEO4J edge information for these source_id(s) to neoedgefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_edges_extract.sql"
    named_args:
      SOURCETABLES: "{{ source_tables }}"
      NEOEDGEFILE: "{{ copy_root }}/extract/{{ neoedgefile }}"
    autocommit: no

#- name: Extract NEO4J node information for this source_id to neonodefile
#  postgresql_query:
#    path_to_script: "{{ role_path }}/files/f100_neo4j_nodes_extract.sql"
#    named_args:
#      SOURCEID: "{{ source_id|int }}"
#      NEONODEFILE: "{{ copy_root }}/extract/{{ neonodefile }}"
#    autocommit: no

