---

- name: Check fragment path
  stat:
    path: "{{ fragpath }}/fragment"
  register: fragment_path_result

- name: Extract NEO4J node information for this source_id to neonodefile
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (WITH RECURSIVE fragments AS (
                select parent_id, child_id, parent_smiles, child_smiles, hac, rac, ring_smiles
                from v_edge
                where parent_id in (
                select n.id from nonisomol n
                 inner join mol_source ms on ms.nonisomol_id = n.id and ms.source_id = {{ source_id }} )
                union
                 select c.parent_id, c.child_id, c.parent_smiles, c.child_smiles, c.hac, c.rac, c.ring_smiles
                 from v_edge c
                 inner join fragments p on c.parent_id = p.child_id
                ) select f1.parent_smiles, f1.hac, f1.rac, f1.ring_smiles, NULL,'F2' as label
                 from fragments f1
                 inner join nonisomol non on non.smiles = f1.parent_smiles
                union
                select f2.child_smiles, non.hac, non.rac, non.ring_smiles, NULL, 'F2'
                 from fragments f2
                 inner join nonisomol non on non.smiles = f2.child_smiles
                 where NOT EXISTS (SELECT 1 FROM v_edge ep WHERE ep.parent_smiles = f2.child_smiles) )
                 TO '{{ fragpath }}/fragment/{{ neonodefile }}' DELIMITER ',' CSV"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"

- name: Extract NEO4J edge information for this source_id to neoedgefile
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=off --set ON_ERROR_STOP=on
     -c "\COPY (with RECURSIVE fragments AS (
             select parent_smiles, child_smiles, label, 'FRAG', parent_id, child_id
             from v_edge
             where parent_id in (
              select n.id from nonisomol n
               inner join mol_source ms on ms.nonisomol_id = n.id
               where ms.source_id = {{ source_id }})
             union
               select c.parent_smiles, c.child_smiles, c.label, 'FRAG', c.parent_id, c.child_id
               from v_edge c
               inner join fragments p on c.parent_id = p.child_id
            ) select parent_smiles, child_smiles, label, 'FRAG' from fragments)
            TO '{{ fragpath }}/fragment/{{ neoedgefile }}' DELIMITER ',' CSV"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"
