---

- name: Extract NEO4J node information for this source_id to neonodefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_nodes_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      NEONODEFILE: "{{ copy_root }}/extract/{{ neonodefile }}"
    autocommit: no

- name: Extract NEO4J edge information for this source_id to neoedgefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_edges_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      NEOEDGEFILE: "{{ copy_root }}/extract/{{ neoedgefile }}"
    autocommit: no

- name: Extract supporting information for this source_id / extract to various files
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_supporting_info_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      GRAPHVERSION: "{{ neo4j_graph_version }}"
      PROCESSID: "{{ process_id }}"
      ISOMOLEDGEFILE: "{{ copy_root }}/extract/{{ isomoledgefile }}"
      ISOMOLNODEFILE: "{{ copy_root }}/extract/{{ isomolnodefile }}"
      ISOSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ isosupmoledgefile }}"
      MOLSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ molsupmoledgefile }}"
      SUPNODEFILE: "{{ copy_root }}/extract/{{ supnodefile }}"
      SUPMOLNODEFILE: "{{ copy_root }}/extract/{{ supmolnodefile }}"
    autocommit: no

- name: Extract vendor specific supporting information for this source_id / extract
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100-neo4j-vendor-{{ vendor }}.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"
    autocommit: no


