---

# This files contains tasks that are primarliy mol_source driven.
#
# As these are relatively small/fast queries they should be ok to run in series and so can be gathered here.
#

# Common Mol_source related extract scripts
- name: Template the main extract script
  template:
    src: sql/f100_neo4j_supporting_info_extract.sql.j2
    dest: "{{ reppath }}/sql/f100_neo4j_supporting_info_extract.sql"
  vars:
    SOURCEIDS: "{{ source_ids }}"
    GRAPHVERSION: "{{ neo4j_graph_version }}"
    PROCESSID: "{{ process_id }}"
    ISOMOLEDGEFILE: "{{ copy_root }}/extract/{{ isomoledgefile }}"
    ISOMOLNODEFILE: "{{ copy_root }}/extract/{{ isomolnodefile }}"
    ISOSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ isosupmoledgefile }}"
    MOLSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ molsupmoledgefile }}"
    SUPNODEFILE: "{{ copy_root }}/extract/{{ supnodefile }}"
    SUPMOLNODEFILE: "{{ copy_root }}/extract/{{ supmolnodefile }}"

- name: Extract supporting information for this source_id / extract to various files
  postgresql_query:
    path_to_script: "{{ reppath }}/sql/f100_neo4j_supporting_info_extract.sql"
    autocommit: no

# Vendor specific extract scripts

#- name: Extract vendor specific supporting information for this source_id / extract
#  postgresql_query:
#    path_to_script: "{{ role_path }}/files/{{ vendor }}/f100-neo4j-vendor-suppliermol.sql"
#    named_args:
#      SOURCEID: "{{ source_id|int }}"
#      SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"
#    autocommit: no

- name: Template the vendor specific extract script where a single vendor is defined
  template:
    src: sql/{{ extracts[0].lib.vendor }}/f100-neo4j-vendor-suppliermol.sql.j2
    dest: "{{ reppath }}/sql/f100-neo4j-vendor-suppliermol.sql"
  vars:
    SOURCEIDS: "{{ source_ids }}"
    SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"
  when: source_id|length == 1

# This uses the combined_vendor parameter when the number of sourced requested is greater than 1.
- name: Template the vendor specific extract script where multiple vendors are defined
  template:
    src: sql/{{ combined_vendor }}/f100-neo4j-vendor-suppliermol.sql.j2
    dest: "{{ reppath }}/sql/f100-neo4j-vendor-suppliermol.sql"
  vars:
    SOURCEIDS: "{{ source_ids }}"
    SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"
  when: source_id|length > 1

- name: Extract supporting information for this source_id / extract to various files
  postgresql_query:
    path_to_script: "{{ reppath }}/sql/f100-neo4j-vendor-suppliermol.sql"
    autocommit: no
