---

# This files contains tasks that are primarliy mol_source driven.
#
# As these are relatively small/fast queries they should be ok to run in series and so can be gathered here.
#

# Common Mol_source related extract scripts
- name: Template the main extract script
  template:
    src: sql/f100_neo4j_supporting_info_extract.sql.j2
    dest: "{{ reppath }}/sql/f100_neo4j_supporting_info_extract.sql"
  vars:
    SOURCEIDS: "{{ source_ids }}"
    GRAPHVERSION: "{{ neo4j_graph_version }}"
    PROCESSID: "{{ process_id }}"
    ISOMOLEDGEFILE: "{{ copy_root }}/extract/{{ isomoledgefile }}"
    ISOMOLNODEFILE: "{{ copy_root }}/extract/{{ isomolnodefile }}"
    ISOSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ isosupmoledgefile }}"
    MOLSUPMOLEDGEFILE: "{{ copy_root }}/extract/{{ molsupmoledgefile }}"
    SUPNODEFILE: "{{ copy_root }}/extract/{{ supnodefile }}"
    SUPMOLNODEFILE: "{{ copy_root }}/extract/{{ supmolnodefile }}"

- name: Extract supporting information for this source_id / extract to various files
  postgresql_query:
    path_to_script: "{{ reppath }}/sql/f100_neo4j_supporting_info_extract.sql"
    autocommit: no

# Supplier molecule extract scripts

- name: Template the supplier molecule extract script
  template:
    src: sql/f100-neo4j-vendor-suppliermol.sql.j2
    dest: "{{ reppath }}/sql/f100-neo4j-vendor-suppliermol.sql"
  vars:
    SOURCEIDS: "{{ source_ids }}"
    SUPMOLSUPEDGEFILE: "{{ copy_root }}/extract/{{ supmolsupedgefile }}"

- name: Extract the supplier molecule information for these source_ids
  postgresql_query:
    path_to_script: "{{ reppath }}/sql/f100-neo4j-vendor-suppliermol.sql"
    autocommit: no
