---

- name: Extract NEO4J node information for this source_id to neonodefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_nodes_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      OUTFILE: "{{ copy_root }}/extract/{{ neonodefile }}"
    autocommit: no

- name: Extract NEO4J edge information for this source_id to neoedgefile
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f100_neo4j_edges_extract.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
      OUTFILE: "{{ copy_root }}/extract/{{ neoedgefile }}"
    autocommit: no

# Pack all files to '.gz' files -1 should compress more quickly.
# We run this on (delegate to) the DB server...

- name: gzip extract directory for upload
  shell: gzip -1 *.csv
  args:
    chdir: "{{ copy_root }}/extract"
  become: yes
  become_user: "{{ db_user_account }}"
  delegate_to: "{{ groups['dbservers'][0] }}"
