---

# Database server specification
aws_keypair_name: nf-pcluster
aws_db_instance_type: t3a.2xlarge
aws_vpc_subnet_id: SetMe
aws_vpc_id: SetMe

aws_default_region: "{{ lookup('env', 'AWS_REGION') }}"
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
