---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml


reppath: "{{ role_path }}/../../.."

datapath: SetMe
standpath: SetMe
fragpath: SetMe

# The following is used (amongst other things)
# to load vendor-specific variables...
vendor: SetMe
# The user is required tp specify the version on the command-line
version: SetMe

# The (AWS S3) location of vendor RAW data
# a source for standardisation.
bucket: im-fragnet

# AWS credentials for bucket access
aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
