---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml


reppath: "{{ role_path }}/../../.."

datapath: SetMe
standpath: SetMe
fragpath: SetMe

# The vendor. Typically a vendor and collection,
# like 'chemspace_bb' or 'xchem_dsip'.
vendor: SetMe
# The user is required tp specify the version on the command-line
version: SetMe

# Add this fileset to an existing source
# (typically when inserting files from a large vendor progressively)
add_file: no
