---

# Container for backup and recovery
backup_container_image: informaticsmatters/sql-backup
backup_container_tag: stable

backup_volume_is_s3: no
backup_volume_s3_url: ''
backup_volume_s3_url_request_style: use_path_request_style
backup_s3_bucket_name: ''
backup_s3_access_key_id: ''
backup_s3_secret_access_key: ''

# The database server's backup directory.
# This *MUST* match the directory
# mapped into the PostgreSQL container.
# copy_root: /pgdata-backup
backup_root: "{{ database[deployment].backup_directory }}"
port: "{{ database[deployment].port }}"
db: "{{ database[deployment].db }}"
login_user: "{{ database[deployment].login_user }}"
login_password: "{{ database[deployment].login_password }}"

#db_root and db_backup_root are used by the copy-database.yaml tasks.

# The DB server's database root directory
# (there will be a pgdata directory in here)
db_root: /pgdata
# Where to copy the data to
db_backup_root: /pgdata-backup