---

# Variables that a user might want to change
# through the command-line or a parameter file.
#
# Less common variables can be found in vars/main.yaml

reppath: "{{ role_path }}/../../.."

# Base path for all folders used in the combination.
# This should be created by the user before the run
# It should normally be different to the repo path and ideally should start with a "/".
runpath: SetMe

# The following defines the libraries to combine.
# 'combine' is a list of 'lib' declarations that define the libraries to combine.
#
# The source of a library is one of 's3' or 'disk'.
# If it's s3 credentials need to be provided.
# 'lib.path' is used as a prefix when listing data when the source is 's3'
# or as a filesystem path when the source is 'disk'.
#
# The file 'combine-parameters.template' provides good usage examples.
combine:
- lib:
    path: 'SetMe'
    data_source: 'SetMe'

# Workflow directories
# Note that files will be kept zipped all the way through.

# If the user wants to add extracts from disk they should be placed here
extract_path: "{{ runpath }}/extract"

# The data path defined where S3 files are originally copied to and where local files are copied to.
data_path: "{{ runpath }}/data"
# Files are them moved to the work path renamed to <extract_no><file_name>
work_path: "{{ runpath }}/work"
# Following the combination exercise, result files will be stored here
combine_path: "{{ runpath }}/combine"
# This contains log files.
log_path: "{{ runpath }}/logs"
# Directory for nextflow work files
next_path: "{{ runpath }}/nextflow"

# Destination?
# One of 's3' or 'disk'.
output_destination: s3
# The S3 location for the destination of extracted data
# Used if 'output_destination' is 's3'
s3_out_bucket: im-fragnet
s3_out_bucket_requires_encryption: no
s3_out_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
s3_out_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
s3_out_region: "{{ lookup('env', 'AWS_REGION')|default('eu-central-1', true) }}"
s3_out_url: "{{ lookup('env', 'S3_URL') }}"
