---

# Expectation here is that we're using a dynamic inventory.
# Ansible's ec2.py does this for us.

- hosts: all

  vars:
    pip_install_packages:
    - name: docker
  roles:
  - role: geerlingguy.pip
    become: yes
  - role: geerlingguy.docker
    become: yes
  - role: db-server-configure
    become: yes
