---
# This version of backup with copy the database to the backup location.
# It requires the container to be stopped.
- hosts: all
  tasks:
  - include_role:
      name: configure
      tasks_from: stop-database.yaml
  - include_role:
      name: backup
      tasks_from: copy-database.yaml
  - include_role:
      name: configure
      tasks_from: start-database.yaml
