---

- hosts: dbservers[0]
  tasks:

  - include_role:
      name: configure
      tasks_from: stop-database.yaml

  - include_role: backup

  - include_role:
      name: configure
      tasks_from: start-database.yaml
