---

# This performs any finalisation steps required for the standardisation process:
# 1. Removes any working files no longer required (production only).
# 2. Copies any reports to save location in S3 identified by vendor/version/standardisation (production only)

- name: remove working files
  file:
    path: "{{ standpath }}/standardise/standardheader"
    state: absent

- name: remove working files
  shell: rm done-chunk_*
  args:
    chdir: "{{ standpath }}/standardise"
    warn: no

# Finalise report
- name: Write line to report
  blockinfile:
    marker: "<!-- {standardise-init} ANSIBLE MANAGED BLOCK -->"
    path: "{{ standpath }}/standardise/standardise_report.html"
    block: |
      <p>Standardisation play ended on: {{ now(utc=True).isoformat() }}</p>
      <p>Saving Files to logs/{{ vendor }}/{{ version }}/standardise </p>

# Zip files for transfer
- name: Compress files
  shell: gzip *
  args:
    chdir: "{{ standpath }}/standardise"

- name: List files
  find:
    paths: "{{ standpath }}/standardise"
    patterns: '*.gz'
  register: find_result

- name: Extract files
  set_fact:
    files_found: "{{ find_result|json_query('files[*].path')|flatten }}"

- name: Display files
  debug:
    var: files_found

- name: Transfer files (to S3)
  aws_s3:
    bucket: "{{ bucket }}"
    encrypt: "{{ bucket_requires_encryption|bool }}"
    src: "{{ item }}"
    object: logs/{{ vendor }}/{{ version }}/standardise/{{ item|basename }}
    mode: put
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
  loop: "{{ files_found }}"
  when: deployment=="production"

# Copy log files to Repo
- name: Copy log files to repo
  shell: cp {{ standpath }}/standardise/* {{ logpath }}/log/{{ vendor }}/{{ version }}/standardise
  when: deployment=="development"

# Backup database if required using the site-backup play.
- include_role:
    name: backup
  when: add_backup|bool
