---
# Gets 'raw' data from data path in repository by vendor

- name: Log line to report
  blockinfile:
    marker: "<!-- {standardise-get} ANSIBLE MANAGED BLOCK -->"
    path: "{{ standpath }}/standardise/standardise_report.html"
    block: |
      <h2>Step: Get Raw Data from Repo</h2>
      <p>Begin: {{ now(utc=True).isoformat() }}</p>

- name: Set raw path
  set_fact:
    raw_path: ../data/{{ vendor|regex_replace('_', '/') }}/{{ version }}

- name: Display raw path
  debug:
    msg: raw_path={{ raw_path }}

- name: Set destination path
  set_fact:
    destination: "{{ datapath }}/data/{{ vendor }}"

- name: Get raw data
  command: cp {{ item }} {{ destination }}
  with_fileglob:
  - "{{ raw_path }}/*.gz"

# Now hand over the get logic to vendor-specific
# un-packing code. It may need to do nothing but
# this is where we do vendor-specific presentation...

- include_tasks: unpack-raw-data-{{ vendor }}.yaml

- name: Log line to report
  blockinfile:
    marker: "<!-- {standardise-get} ANSIBLE MANAGED BLOCK -->"
    path: "{{ standpath }}/standardise/standardise_report.html"
    block: |
      <p>End: {{ now(utc=True).isoformat() }}</p>
