---

- name: Set raw path
  set_fact:
    raw_path: /raw/vendor/{{ bucket_raw_path }}/

- name: Display raw path
  debug:
    var: raw_path

- name: List raw data
  aws_s3:
    bucket: "{{ bucket }}"
    mode: list
    prefix: /raw/vendor/{{ bucket_raw_path }}/
  register: raw_result

# There has to be at least one key in the result....

- name: Check raw data
  assert:
    that: raw_result.s3_keys|length > 0

- name: Display raw file count
  debug:
    msg: Found {{ raw_result.s3_keys|length }} raw files

- name: Get raw data
  aws_s3:
    bucket: "{{ bucket }}"
    mode: get
    object: "{{ item }}"
    dest: "{{ datapath }}/data/{{ vendor }}/"
  with_items: raw_result.s3_keys
