---

- name: Check vendorpath
  stat:
    path: "{{ reppath }}/{{ vendorpath }}"
  register: vendorpath_result

- name: Check run
  stat:
    path: "{{ reppath }}/run"
  register: run_result

- name: Assert expected directories
  assert:
    that:
    - vendorpath_result.stat.isdir is defined
    - vendorpath_result.stat.isdir
    - run_result.stat.isdir is defined
    - run_result.stat.isdir

- name: Create directories
  file:
    path: "{{ item }}"
  loop:
  - "{{ datapath }}/data/{{ vendor }}"
  - "{{ fragpath }}/fragment"
  - "{{ standpath }}/standardise"

- name: Check fragpass
  stat:
    path: "{{ reppath }}/run/fragpass"
  register: fragpass_result

- name: Assert fragpass
  assert:
    that:
    - fragpass_result.stat.exists

- name: Set fragpass state
  file:
    path: "{{ reppath }}/run/fragpass"
    mode: "0600"
