---

- name: Display chunk
  debug:
    var: item

- name: Extract standard header
  shell: cat standardheader > standardised.tab
  args:
    chdir: "{{ standpath }}/standardise"

- name: Extract standard header
  shell: cat {{ item }} >> standardised.tab
  args:
    chdir: "{{ standpath }}/standardise"

- name: Creating Standardisation tables
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f40_create_stand_database.sql"
    autocommit: yes

- name: Copy chunk
  postgresql_copy:
    copy_from: "{{ standpath }}/standardise/standardised.tab"
    dst: "{{ standardise_copy_table }}"
    columns: "{{ standardise_copy_columns }}"
    options:
      delimiter: '\t'
      header: yes
    autocommit: yes

- name: Load chunk
  postgresql_query:
    path_to_script: "{{ role_path }}/files/f40_load_standardised_data.sql"
    named_args:
      SOURCEID: "{{ source_id }}"
    autocommit: no
