---

- name: Display chunk
  debug:
    var: item

- name: Creating Standardisation tables
  postgresql_query:
    path_to_script: "{{ role_path }}/files/{{ vendor }}/f40_create_stand_database.sql"
    autocommit: yes

#- name: Copy chunk
#  postgresql_copy:
#    copy_from: "{{ item }}"
#    dst: "{{ standardise_copy_table }}"
#    columns: "{{ standardise_copy_columns }}"

- name: Copy chunk
  command: >-
    psql -X -U {{ database[deployment].login_user }} -h {{ database[deployment].login_host }} --echo-all
     --set AUTOCOMMIT=on --set ON_ERROR_STOP=on
     -c "\COPY {{ standardise_copy_table }}({{ standardise_copy_columns }})
         FROM '{{ item }}';"
    {{ database[deployment].db }}
  environment:
    PGPASSWORD: "{{ database[deployment].login_password }}"

- name: Load chunk
  postgresql_query:
    path_to_script: "{{ role_path }}/files/{{ vendor }}/f40_load_standardised_data.sql"
    named_args:
      SOURCEID: "{{ source_id|int }}"
    autocommit: no
