---

- name: Include vendor-specific varaibles
  include_vars:
    file: "{{ vendor }}-variables.yaml"

- import_tasks: initialise-frag-process.yaml
- import_tasks: get-raw-data.yaml
- import_tasks: standardise-file.yaml
- import_tasks: load-standardissed-data.yaml
