---

# Invoked from some vendor-specific unpack logic to decompress
# all .gz files in the directory. The expectation is that 'destination'
# is where the (unpacked) data is stored.

- name: Assert destination
  assert:
    that:
    - destination is defined
    - destination|string|length > 0

# Unpack all '.gz' files...

- name: Unpack the single file
  unarchive:
    copy: no
    creates: "{{ item|regex_replace('.gz') }}"
    src: "{{ item }}"
    dest: "{{ item|regex_replace('.gz') }}"
  with_fileglob:
  - "{{ destination }}/*.gz"
