---

- name: Assert control variables
  assert:
    that:
    - aws_default_region|string|length > 0
    - aws_access_key_id|string|length > 0
    - aws_secret_access_key|string|length > 0

# Look for server - it'll be tagged "Purpose: fragmentor-database"

- name: Lookup DB server
  ec2_instance_info:
    filters:
      "tag:Purpose": fragmentor-database
  register: ec2_result

# Delete server

- name: Delete DB server
  ec2:
    instance_ids:
    - "{{ ec2_result.instances[0].instance_id }}"
    wait: yes
    wait_timeout: 600
    state: absent
  when:
  - ec2_result.instances|length == 1
