---

- name: Load provider-specific variables
  include_vars: defaults/variables-{{ db_cloud_provider }}.yaml

- import_tasks: create-server-{{ db_cloud_provider }}.yaml
  when: db_server_state == 'present'
- import_tasks: delete-server-{{ db_cloud_provider }}.yaml
  when: db_server_state != 'present'