---

- name: Load provider-specific variables
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
    - defaults/variables-{{ database_cloud_provider }}.yaml
    - defaults/default.yaml

- import_tasks: create-server-{{ database_cloud_provider }}.yaml
  when: db_server_state == 'present'
- import_tasks: delete-server-{{ database_cloud_provider }}.yaml
  when: db_server_state != 'present'
