---
name: lint and build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.
# Here we build container images but don't push them
# and therefore do not require docker credentials.

on:
  push:
    branches:
    - '!master'
  pull_request:
    branches:
    - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Build fragmentor
      uses: docker/build-push-action@v1
      with:
        repository: informaticsmatters/fragmentor
        push: false
    - name: Build player
      uses: docker/build-push-action@v1
      with:
        repository: informaticsmatters/fragmentor-player
        push: false
