---
name: lint and publish latest

# Actions on the main/master branch for every change.

on:
  push:
    branches:
    - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +

  publish-latest:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push fragmentor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: informaticsmatters/fragmentor:latest
    - name: Build and push player
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile-player
        push: true
        tags: informaticsmatters/fragmentor-player:latest
