---
name: lint and build

# Actions that take place on branches
# or are driven by pull-requests to the main/master branch.
# Here we lint the code and build container images but don't push them
# and therefore do not require docker credentials.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - 'master'
  # Additionally, to catch an early build-dependency problems,
  # always build the image at 08:07 on Mondays (day 1).
  # This is handy to catch any build problems caused by modules we import.
  schedule:
  - cron: '7 8 * * 1'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Lint
      run: |
        yamllint .
        find . -type f -name '*.yaml.j2' -exec yamllint {} +

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Build fragmentor
      uses: docker/build-push-action@v6
    - name: Build player
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile-player
