---
name: publish latest images

on:
  push:
    branches:
    - master

jobs:
  publish_latest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push fragmentor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: informaticsmatters/fragmentor:latest
    - name: Build and push player
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile-player
        push: true
        tags: informaticsmatters/fragmentor-player:latest
