---
name: publish stable

# Actions for an 'official' tag.
#
# An official tag is a 2 or 3-digit value (i.e. 'N.N[.N]').
# We publish images using the tag as a tag and one using 'stable' as s tag.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)
#
# For automated deployment we expect the following in the environment: -
#
# (n/a)

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+'

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push fragmentor
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          informaticsmatters/fragmentor:stable
          informaticsmatters/fragmentor:${{ env.GITHUB_REF_SLUG }}
    - name: Build and push player
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile-player
        push: true
        tags: |
          informaticsmatters/fragmentor-player:stable
          informaticsmatters/fragmentor-player:${{ env.GITHUB_REF_SLUG }}
