---

# The ansible unpack tasks - can be vendor specific
unpacker: chemspace_bb
# Python script used to standardise the molecules
standardiser: frag.standardise.scripts.chemspace_bb.standardise_chemspace_bb_pricing_compounds
# Input file template (unzipped) expected by standardiser. If there are multiple files this can be a glob.
standinputfile: chemspace_bb.txt
# Upload table template to match fields in standardised compounds.
standardise_copy_table: i_mols_chemspace
# Fields to upload to table (used in copy statement).
standardise_copy_columns: osmiles,isosmiles,nonisosmiles,hac,cmpd_id,price
