---

standardiser: frag.standardise.scripts.dsip.standardise_xchem_compounds
standchunksize: 250
standinputfile: dsip.txt

standardise_copy_cmd: i_mols_dsip(osmiles, isosmiles, nonisosmiles, hac, cmpd_id)
