---
# Variables that a user might want to change
# through the command-line or a parameter file.

# Standardisation Rate in molecules processed per minute by a single
# standardisation python script. This approximate parameter is used to tune
# the nextflow_timeout_minutes in conjunction with the number
# of CPUs and Vendor_molecules.
standardisation_mols_minute: 4500
nextflow_timeout_calc: 0

# Safety factor is used in case, for example, other processes are on the machine
safety_factor: 50

# Default nextflow parameters for development.
# These are overwritten in production deployment based on the
# size of the vendor input files.
nextflow_timeout_minutes: 30
nextflow_poll_period_minutes: 1
standchunksize: 250
standchunksize_calc: 0

# Chunk size to control size of transactions in
# uploading standardised file data to database
standchunk: 1000000

# Compound Prefix used in creating the compound-id's.
# This is overridden if required in the vendor specific files.
standard_compound_id_prefix: None
# Field in SDF file to be used for compound id.
# This is overridden if required in the vendor specific files.
standard_compound_id_field: None
# Field in file to be used to split records in the case where it is not a line.
# This is overridden if required in
# the vendor specific files.
standsplittoken: None
