---

standardiser: frag.standardise.scripts.molport.standardise_molport_compounds
standchunksize: 1500
standinputfile: iis_smiles-*.txt

standardise_copy_table: i_mols_molport
standardise_copy_columns: osmiles, isosmiles, nonisosmiles, hac, cmpd_id, price_1, price_5, price_50, lead_time
