---

# The ansible unpack tasks - can be vendor specific
unpacker: decompress-gz-all
# Python script used to standardise the molecules
standardiser: frag.standardise.scripts.molport.standardise_molport_compounds
# Input file template (unzipped) expected by standardiser. If there are multiple files this can be a glob.
standinputfile: iis_smiles-*.txt
# Upload table template to match fields in standardised compounds.
standardise_copy_table: i_mols_molport
# Fields to upload to table (used in copy statement).
standardise_copy_columns: osmiles, isosmiles, nonisosmiles, hac, cmpd_id, price_1, price_5, price_50, lead_time
