---

# The ansible unpack tasks - can be vendor specific
unpacker: decompress-gz-all
# Python script used to standardise the molecules
standardiser: frag.standardise.scripts.sdf.standardise_sdf_compounds
# Input file template (unzipped) expected by standardiser. If there are multiple files this can be a glob.
standinputfile: test.sdf
# Token used to split records.
standsplittoken: $$$$
# Coumpound Prefix used in creating the compound-id's. For the other vendors this is hardcoded as the company name.
standard_compound_id_prefix: SDF
# Field in SDF file to be used for compound id. For the other vendors this is hardcoded as the company name.
standard_compound_id_field: mr_id
# Upload table template to match fields in standardised compounds.
standardise_copy_table: i_mols_sdf
# Fields to upload to table (used in copy statement).
standardise_copy_columns: osmiles,isosmiles,nonisosmiles,hac,cmpd_id
